name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afc11e20c954c71d8f338df8b513a44d1684a389f49743bd607f0880243aa91d"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
