name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "444e6faf973050d79a8ba88f875dd23e98a072b25dc8b1cbcc9f9c7207b3ce5f"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
