name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb973b20fb9c712c6375e682f2803b2e8bcd91e0b2abbe7bf4e16d254ab0f8f"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
