name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fe4ad43e2666c9cb877d67b952f1184f6a553d758200fd29794a54d312db6e5"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
