name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05c387fbffe9a9b1138d884f0a7eb8aba8f8120865954f6fe6b1595025c611c6"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
