name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b2ddc262fa2f8ceede7aaf12c422f8fb0de3dfcba3512ffec6f05f6a482f1df"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
