name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75aabc0361468f10935ad81b5be6ff9036d7df775971a62467461fccb9b5c5af"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
