name = "ChairMC"
author = "SobakinTech"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e1a4981afd07f86dc95eb3d19c528dc72884c3fbfa72c0f209fc9bab9d49c79"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
