name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33b1cd51b2efbbb3ad17bc921a7c9d7cfd4ed3812538ae74f90c7ec690b1a8fc"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
