name = "ChairMC"
author = "SobakinTech"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2178949555624074d152b0558e9e733175e7e5c35f31ea549993ee90f9cff91"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
