name = "ChairMC"
author = "SobakinTech"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b40ce808a66d158dfcf3e905a7c7d2fcb2d4b4e85381c51428ef63ec1d34e3"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
