name = "ChairMC"
author = "SobakinTech"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d40ae1f03cdc1e2e1bfaef6328229ee1353b5fb5d17bccb965577f65a2419e"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
